[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ahclib"
version = "0.1.0"
description = "AHCのための並列実行とoptuna最適化ツール"
authors = [
    { name = "titan23", email = "titan23.kyopuro@gmail.com" }
]
license = { text = "特になし" }
urls = { "Homepage" = "https://github.com/titan-23/ahclib" }
requires-python = ">=3.10"
keywords = ["AtCoder", "AHC", "heuristic", "tools"]
dependencies = [
    "optuna>=4.1.0",
]
readme = "README.md"

[tool.setuptools.packages.find]
where = ["ahclib"]
